SELECT DISTINCT
    P.NAME
FROM
    MOVIES M
    JOIN DIRECTORS D ON M.ID = D.MOVIE_ID
    JOIN PEOPLE P ON D.PERSON_ID = P.ID
    JOIN RATINGS R ON M.ID = R.MOVIE_ID
WHERE
    R.RATING >= 9.0
ORDER BY
    P.NAME ASC;
