SELECT
    M.TITLE
FROM
    MOVIES M
    JOIN STARS S ON M.ID = S.MOVIE_ID
    JOIN PEOPLE P ON S.PERSON_ID = P.ID
    JOIN RATINGS R ON M.ID = R.MOVIE_ID
WHERE
    P.NAME = 'Chadwick Boseman'
ORDER BY R.RATING DESC
LIMIT 5;
